//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VisualStudioDemo.rc
//
#define IDC_APPLY                       3
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define IDS_STRING_NOT_FOUND_FMT        102
#define IDS_BUILD_TOOLBAR               103
#define IDS_RESOURCE_TOOLBAR            104
#define ID_VIEW_TOOLBOX                 105
#define IDS_EDIT_TOOLBAR                106
#define IDS_CARET_POS                   107
#define ID_EDIT_FINDNEXT                108
#define ID_VIEW_EDITCTRL                112
#define ID_EDIT_FINDPREV                113
#define ID_EDIT_SHOWHINT                116
#define IDS_EDITFAILED                  121
#define IDS_PGUPFAILED                  122
#define IDR_MAINFRAME                   128
#define IDR_BCGDEVTYPE0                 129
#define IDR_BCGDEVTYPE_CPP              130
#define IDR_BCGDEVTYPE_WEB              131
#define IDR_CONTEXT_MENU                132
#define IDI_CLASS_VIEW                  132
#define IDR_POPUP_TOOLBAR               133
#define IDI_RES_VIEW                    133
#define IDI_FILE_VIEW                   134
#define IDB_CLASS_VIEW                  135
#define IDI_OUTPUT_BAR                  135
#define IDB_RESOURCE_VIEW               136
#define IDI_WATCH_BAR                   136
#define IDB_FILE_VIEW                   137
#define IDR_BUILD                       138
#define IDR_POPUP_SORT                  139
#define IDB_LOGO                        141
#define IDR_MENU_IMAGES                 142
#define IDR_POPUP_OUTPUT                144
#define IDR_POPUP_MAIN_AREA             146
#define IDR_SORT                        146
#define IDR_MENU_DIRS                   147
#define IDI_PROPERTIES_BAR              153
#define IDR_SOLUTION_EXPLORER           154
#define IDR_EDIT                        155
#define IDB_START                       156
#define IDI_TOOLBOX_BAR                 157
#define IDI_CLASS_VIEW_HC               158
#define IDI_CLASS_VIEW_2012             159
#define IDI_FILE_VIEW_2012              160
#define IDR_MENU_ARGS                   161
#define IDR_POPUP_SOLUTION              162
#define IDR_POPUP_RESOURCE              163
#define IDR_POPUP_CONTROLBAR            164
#define IDB_TOOLS_PAGE1                 168
#define IDB_TOOLS_PAGE2                 169
#define IDD_FINDDIALOG                  169
#define IDB_TOOLS_PAGE3                 170
#define IDB_IMG_INTELLISENSE            173
#define IDR_POPUP_SELECTIONMARGIN       176
#define IDR_POPUP_MDITABS               177
#define IDR_POPUP_DROP_MDITABS          178
#define IDD_APP_LOOK                    180
#define IDR_EDITOR_XML_SETTINGS_WEB     182
#define IDR_EDITOR_XML_SETTINGS_CPP     183
#define IDB_IMG_INTELLISENSE_2012       184
#define IDB_MENU_IMAGES_HC              185
#define IDB_MAINFRAME_HC                186
#define IDB_BUILD_HC                    187
#define IDB_EDIT_HC                     188
#define IDI_FILE_VIEW_HC                189
#define IDB_IMG_INTELLISENSE_HC         189
#define IDI_RES_VIEW_HC                 190
#define IDI_TOOLBOX_BAR_HC              191
#define IDI_PROPERTIES_BAR_HC           192
#define IDD_NEW_FILE                    193
#define IDI_WATCH_BAR_HC                194
#define IDI_OUTPUT_BAR_HC               195
#define IDB_SOLUTION_EXPLORER_HC        195
#define IDB_CLASS_VIEW_HC               197
#define IDB_SORT_HC                     198
#define IDB_START_HC                    199
#define IDB_TOOLS_PAGE1_HC              200
#define IDD_GOTO_LINE                   201
#define IDB_TOOLS_PAGE2_HC              201
#define IDB_TOOLS_PAGE3_HC              202
#define IDB_FILE_VIEW_HC                203
#define IDI_OUTPUT_BAR_2012             204
#define IDI_WATCH_BAR_2012              205
#define IDB_RESOURCE_VIEW_HC            206
#define IDB_BREAK                       207
#define IDB_CURRENT                     208
#define IDB_START_HC_2010               210
#define IDR_EDITOR_XML_SETTINGS_BAS     210
#define IDR_EDITOR_XML_SETTINGS_PAS     211
#define IDR_EDITOR_XML_SETTINGS_ASM     212
#define IDR_EDITOR_XML_SETTINGS_CS      213
#define IDR_EDITOR_XML_SETTINGS_JS      214
#define IDR_EDITOR_XML_SETTINGS_SQL     215
#define IDR_EDITOR_XML_SETTINGS_XML     217
#define ID_EXAMPLE_CPP                  225
#define ID_EXAMPLE_WEB                  226
#define ID_EXAMPLE_BAS                  227
#define ID_EXAMPLE_PAS                  228
#define ID_EXAMPLE_ASM                  229
#define ID_EXAMPLE_XML                  230
#define ID_EXAMPLE_CS                   231
#define ID_EXAMPLE_JS                   232
#define ID_EXAMPLE_SQL                  233
#define IDR_BCGDEVTYPE_BAS              237
#define IDR_BCGDEVTYPE_PAS              238
#define IDR_BCGDEVTYPE_ASM              239
#define IDR_BCGDEVTYPE_CS               240
#define IDR_BCGDEVTYPE_JS               241
#define IDR_BCGDEVTYPE_SQL              242
#define IDB_START_HC_2012_DARK          243
#define IDR_BCGDEVTYPE_XML              244
#define IDB_START_HC_2012               245
#define IDB_MAINFRAME_2012              246
#define IDB_BUILD_2012                  247
#define IDB_EDIT_2012                   248
#define IDB_MENU_IMAGES_2012            249
#define IDB_TOOLS_PAGE1_2012            250
#define IDB_TOOLS_PAGE2_2012            251
#define IDB_TOOLS_PAGE3_2012            252
#define IDB_CLASS_VIEW_2012             253
#define IDB_SORT_2012                   254
#define IDB_FILE_VIEW_2012              255
#define IDB_RESOURCE_VIEW_2012          256
#define IDI_RES_VIEW_2012               257
#define IDI_TOOLBOX_BAR_2012            258
#define IDI_PROPERTIES_BAR_2012         259
#define IDD_DIALOG1                     262
#define IDD_DIALOG_ABOUT                263
#define IDC_MAIL                        1000
#define IDC_URL                         1001
#define IDC_FINDDIALOG_MATCHWHOLEWORDONLYCHECK 1001
#define IDC_VERSION                     1002
#define IDC_FINDDIALOG_MATCHCASECHECK   1002
#define IDC_FINDDIALOG_REGULAREXPRESSIONCHECK 1003
#define IDC_FINDDIALOG_SEARCHALLOPENDOCUMENTSCHECK 1004
#define IDC_FINDDIALOG_UPRADIO          1005
#define IDC_FINDDIALOG_DOWNRADIO        1006
#define IDC_FINDDIALOG_MARKALLBUTTON    1007
#define IDC_RADIO1                      1007
#define IDC_FINDDIALOG_REGULARBUTTON    1008
#define IDC_RADIO2                      1008
#define IDC_BUTTON1                     1009
#define IDC_RADIO3                      1009
#define IDC_COMBO1                      1010
#define IDC_FINDDIALOG_FINDCOMBO        1011
#define IDC_CHECK1                      1011
#define IDC_EDIT2                       1012
#define IDC_CHECK5                      1012
#define IDC_EDIT3                       1013
#define IDC_CHECK8                      1013
#define IDC_CHECK2                      1014
#define IDC_CHECK9                      1014
#define IDC_CHECK3                      1015
#define IDC_CHECK10                     1015
#define IDC_SHOW_AT_STARTUP             1015
#define IDC_CHECK4                      1016
#define IDC_CHECK11                     1016
#define IDC_CHECK6                      1017
#define IDC_EDIT1                       1017
#define IDC_CHECK12                     1017
#define IDC_CHECK7                      1018
#define IDC_CHECK13                     1018
#define IDC_EDIT4                       1018
#define IDC_XP_COLORS                   1018
#define IDC_LINE                        1018
#define IDC_ACTIVETAB_CLOSE_BUTTON      1018
#define IDC_RADIO4                      1019
#define IDC_RADIO5                      1020
#define IDC_PROP_LIST                   1025
#define IDD_DIALOG_FILENEW              1026
#define IDC_BROWSE                      1027
#define IDC_MFCLINK1                    1028
#define IDC_MFCLINK2                    1029
#define IDC_TEMPLATE_LIST               1043
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_USER_TOOLBAR1           32771
#define ID_VIEW_USER_TOOLBAR2           32772
#define ID_VIEW_USER_TOOLBAR3           32773
#define ID_VIEW_USER_TOOLBAR4           32774
#define ID_VIEW_USER_TOOLBAR5           32775
#define ID_VIEW_USER_TOOLBAR6           32776
#define ID_VIEW_USER_TOOLBAR7           32777
#define ID_VIEW_USER_TOOLBAR8           32778
#define ID_VIEW_USER_TOOLBAR9           32779
#define ID_VIEW_USER_TOOLBAR10          32780
#define ID_VIEW_TOOLBARS                32781
#define ID_VIEW_WORKSPACE               32782
#define ID_VIEW_OUTPUT                  32783
#define ID_WINDOW_MANAGER               32784
#define ID_DUMMY_COMPILE                32787
#define ID_DUMMY_BUILD                  32788
#define ID_DUMMY_STOP_BUILD             32789
#define ID_SORT_MENU                    32789
#define ID_DUMMY_EXECUTE                32790
#define ID_DUMMY_GO                     32791
#define ID_DUMMY_SELECT_ACTIVE_CONFIGURATION 32794
#define ID_DUMMY_REMOVE_ALL_BREAKPOINTS 32796
#define ID_VIEW_BUILD_TOOLBAR           32797
#define ID_DUMMY_REBUILD_ALL            32798
#define ID_DUMMY_CLEAN                  32799
#define IDS_DUMMY_UNDO_ACTION           32800
#define ID_USER_TOOL1                   32806
#define ID_USER_TOOL2                   32807
#define ID_USER_TOOL3                   32808
#define ID_USER_TOOL4                   32809
#define ID_USER_TOOL5                   32810
#define ID_USER_TOOL6                   32811
#define ID_USER_TOOL7                   32812
#define ID_USER_TOOL8                   32813
#define ID_USER_TOOL9                   32814
#define ID_USER_TOOL10                  32815
#define ID_TOOLS_MACRO                  32816
#define ID_TOOLS_ENTRY                  32819
#define ID_OUTPUT_GOTO_ERROR            32833
#define ID_CLASS_DEFINITION             32836
#define ID_CLASS_ADD_MEMEBER_FUNCTION   32837
#define ID_CLASS_ADD_MEMEBER_VARIABLE   32838
#define ID_CLASS_PROPERTIES             32839
#define ID_RESOURCE_OPEN                32840
#define ID_RESOURCE_OPEN_BINARY         32841
#define ID_HELP_KEYBOARDMAP             32845
#define ID_MENU_DIR1                    32847
#define ID_MENU_DIR2                    32848
#define ID_MENU_DIR3                    32849
#define ID_MDITABS_ICONS                32850
#define ID_MDITABS_TOP                  32851
#define ID_MDITABS_BOTTOM               32852
#define ID_VIEW_MDI_TABS                32853
#define ID_MDITABS_CLOSE                32855
#define ID_VIEW_CLASS                   32856
#define ID_VIEW_RESOURCE                32857
#define ID_VIEW_FILE                    32858
#define ID_MENU_ITEM1                   32866
#define ID_MENU_ITEM2                   32867
#define ID_MENU_ITEM3                   32868
#define ID_SORTING_GROUPBYTYPE          32869
#define ID_SORTING_SORTALF              32870
#define ID_SORTING_SORTBYTYPE           32871
#define ID_SORTING_SORTBYACCESS         32872
#define ID_DHELP1                       32873
#define ID_DHELP2                       32874
#define ID_DHELP3                       32875
#define ID_EXPAND                       32878
#define ID_SORTINGPROP                  32879
#define ID_PROPERTIES1                  32880
#define ID_PROPERTIES2                  32881
#define ID_NEW_FOLDER                   32882
#define ID_PROPERTIES                   32883
#define ID_SOLUTION_OPEN                32884
#define ID_SOLUTION_OPEN_WITH           32885
#define ID_FILE_NEW_PROJECT             32886
#define ID_FILE_NEW_BLANK_SOLUTION      32887
#define ID_FILE_OPEN_SOLUTION           32888
#define ID_FILE_CLOSE_SOLUTION          32889
#define ID_FILE_SAVE_ALL                32892
#define ID_TOOLS_DEBUG_PROCESSES        32893
#define ID_TOOLS_CONNECT_TO_DATABASE    32894
#define ID_WINDOW_CLOSE_ALL             32895
#define ID_HELP_SHOW_START              32896
#define ID_VIEW_REFRESH                 32897
#define ID_VIEW_PROPERTIES              32900
#define ID_VIEW_WATCH                   32901
#define ID_VIEW_FULLSCREEN              32902
#define ID_EDIT_TOGGLEBOOKMARK          32925
#define ID_EDIT_NEXTBOOKMARK            32926
#define ID_EDIT_PREVIOUSBOOKMARK        32927
#define ID_EDIT_TOGGLEBREAKPOINT        32928
#define ID_EDIT_CLEAR_ALLBOOKMARKS      32930
#define ID_EDIT_INCREASE_INDENT         32931
#define ID_EDIT_DECREASE_INDENT         32932
#define ID_VIEW_EDIT_TOOLBAR            32933
#define ID_EDIT_LISTMEMBERS             32935
#define IDS_UAT_UNDEFINED               32936
#define IDS_UAT_INSERTDATA              32937
#define IDS_UAT_TYPING                  32937
#define IDS_UAT_DELETEDATA              32938
#define IDS_UAT_DELETE                  32938
#define IDS_UAT_INDENTDATA              32939
#define IDS_UAT_INDENT                  32939
#define IDS_UAT_UNKNOWN                 32940
#define IDS_UAT_CUT                     32941
#define IDS_UAT_PASTE                   32942
#define IDS_UAT_BACKSPACE               32943
#define IDS_UAT_UNINDENT                32944
#define IDS_UAT_DRAGDROP                32945
#define IDS_UAT_TAB                     32946
#define IDS_UAT_ENTER                   32947
#define ID_EDIT_FIND_COMBO              32948
#define ID_TOOLS_OPTIONS                32949
#define ID_VIEW_APP_LOOK                32950
#define ID_HELP_WEB                     32951
#define ID_EDIT_HIDESELECTION           32952
#define ID_EDIT_TOGGLEOUTLINING         32953
#define ID_EDIT_STOPHIDINGCURRENT       32954
#define ID_EDIT_TOGGLEALLOUTLINING      32955
#define ID_EDIT_COLLAPSETODEFINITIONS   32956
#define ID_EDIT_STOPOUTLINING           32957
#define ID_EDIT_AUTOOUTLINING           32958
#define ID_EDIT_ENABLEOUTLINING         32959
#define ID_EDIT_NEXT_WORD               32960
#define ID_EDIT_LINENUMBERS             32961
#define IDS_UAT_REPLACE                 32962
#define ID_EDIT_GOTO_LINE               32963
#define ID_MDI_NEW_VERT_GROUP           32965
#define ID_MDI_NEW_HORZ_TAB_GROUP       32966
#define ID_MDI_MOVE_TO_PREV_GROUP       32967
#define ID_MDI_CANCEL                   32968
#define ID_MDI_MOVE_TO_NEXT_GROUP       32969
#define ID_TOOLBOX                      32970
#define ID_MDI_TABBED_DOCUMENT          32974
#define ID_MDI_TABS_FILE_CLOSE          32975
#define ID_WINDOW_RESET_LAYOUT          32978
#define ID_EDIT_COMPLETEWORD            32979
#define ID_EDIT_VIEWWHITESPACE          32980
#define ID_FILE_NEWEMPTY                32981
#define ID_FILE_NEWEMPTY32982           32982

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        265
#define _APS_NEXT_COMMAND_VALUE         32983
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           123
#endif
#endif
